services:
  api:
    build: 
      context: .
      dockerfile: apps/checkout_api/Dockerfile
    ports:
    - "8000:8000"
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salesdb
    ports:
      - "5432:5432"
